<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>QCP.Logging</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Serilog" Version="4.2.0" />


        <PackageReference Include="OpenTelemetry" Version="1.11.1" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.11.1" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.11.1" />
        <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.11.0-beta.1" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.11.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.11.0-beta.1" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.11.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.11.0" />
        <PackageReference Include="Serilog.Enrichers.CallerInfo" Version="1.0.5" />
        <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
        <PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
        <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
        <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
        <PackageReference Include="Serilog.Exceptions.EntityFrameworkCore" Version="8.4.0" />
        <PackageReference Include="Serilog.Exceptions.Refit" Version="8.4.0" />
        <PackageReference Include="Serilog.Exceptions.SqlServer" Version="8.4.0" />
        <PackageReference Include="Serilog.Sinks.Grafana.Loki" Version="8.3.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
        <PackageReference Include="Serilog.Enrichers.OpenTelemetry" Version="1.0.1" />
      <PackageReference  Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.4" />
      <PackageReference  Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
      <PackageReference  Include="Newtonsoft.Json" Version="13.0.3" />
      



    </ItemGroup>



</Project>
